# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone X",
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("DashControlSnapshots")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
